name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # or 'temurin', 'zulu', etc.
          java-package: 'jdk'
          check-latest: false
          server-id: 'github'
          server-username: 'GITHUB_ACTOR'
          server-password: 'GITHUB_TOKEN'
          overwrite-settings: true
          job-status: 'success'
          token: ${{ secrets.GITHUB_TOKEN }}  # Ensure to use correct secret

      - name: Build the project
        run: ./mvnw package # or `mvn package` if you have Maven installed

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1.0.0

      - name: Build Docker image
        run: docker build -t empapp .

      - name: Tag Docker image
        run: docker tag empapp:latest 225989376232.dkr.ecr.us-east-1.amazonaws.com/empapp/empapp:latest

      - name: Push Docker image to Amazon ECR
        run: docker push 225989376232.dkr.ecr.us-east-1.amazonaws.com/empapp/empapp:latest

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: .github/workflows/task-definition.json
          service: TestEmp
          cluster: EmpDemo
          wait-for-service-stability: true

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1